default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: description_reader_development

test:
  <<: *default
  database: description_reader_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
